DPR2-2523 replace superagent with node native http (#667)
Superagent was used in the streaming download and it was automatically
unzipping and consuming the entire stream before the even upstream.pipe
was called.
This was causing the below error:
```
Error: end() has already been called, so it's too late to start piping
    at response.pipe (/app/node_modules/superagent/lib/node/index.js:890:13)
    at Request.<anonymous> (/app/node_modules/@ministryofjustice/hmpps-digital-prison-reporting-frontend/dpr/data/restClient.js:73:16)
```
And the application crashed.
These changes replace superagent with the native nodejs http modules in
order to have full visibility and control and avoid behaviour behind the
scenes.